### ISSUE TITLE
Implementing the methods get user follows and followers

### ISSUE THREAD

**Issue by onurozmenn** [dmytrostriletskyi/threads-net#12]
If you add these functions that will be great. I tried but I can get only Instagram followers.

**Comment by PittCaleb** [comment]
Is this not a duplicate of issue #10?

**Comment by onurozmenn** [comment]
Oh sorry about that. I didnt see. Should i delete this issue?

**Comment by onurozmenn** [comment]
Oh sorry about that. I didnt see. Should i delete this issue?

**Comment by dmytrostriletskyi** [comment]
Duplicate of https://github.com/dmytrostriletskyi/threads-net/issues/10
