### ISSUE TITLE
How do I find the ID?

### ISSUE THREAD

**Issue by trojanx6** [dmytrostriletskyi/threads-net#14]
threads.get_user_threads(id=314216)

How can I find ID= defined number in code without using API?

**Comment by dmytrostriletskyi** [comment]
Hi, @trojanx6, thank you for the issue and interest to the library! 👍 

I have just made a new release (v0.0.8) and now you can easily fetch a user's identifier by its username — https://github.com/dmytrostriletskyi/threads-net#get-user-identifier

And then use this user's identifier in all other methods.
