### ISSUE TITLE
This code is nowhere to be found?

### ISSUE THREAD

**Issue by trojanx6** [dmytrostriletskyi/threads-net#15]
There is no such code, how can you get data from it?
self.user_info_by_username_v1(username=username).dict().get('pk')

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net#disclaimer

> For all the Instagram-related thing other well-know and already stable library called [instagrapi] (https://github.com/adw0rd/instagrapi) is used in threads-net.

https://github.com/dmytrostriletskyi/threads-net/blob/main/threads/main.py#L88
https://github.com/dmytrostriletskyi/threads-net/blob/main/threads/main.py#L33
https://github.com/dmytrostriletskyi/threads-net/blob/main/threads/main.py#L20
