### ISSUE TITLE
Legacy code

### ISSUE THREAD

**Issue by trojanx6** [dmytrostriletskyi/threads-net#17]
Can you give the old version of the code, my code exploded because there are no titles, thanks in advance

**Comment by FastFingertips** [comment]
-> [Releases](https://github.com/dmytrostriletskyi/threads-net/releases)

**Comment by dmytrostriletskyi** [comment]
Hi, @trojanx6! 

Thank you for the interest to the project.

1. Can you please try new release? I have just dropped `v0.0.12` — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.12
2. If you still experience any error, please, provide a traceback and detailed instructions on how to reproduce it.

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net/issues/18
