### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cop-discord** [dmytrostriletskyi/threads-net#19]
user = threads.get_user(id=user_id)
7|api  |   File "/root/.mamba/envs/rival/lib/python3.9/site-packages/threads/main.py", line 167, in get_user
7|api  |     return response.json()
7|api  |   File "/root/.mamba/envs/rival/lib/python3.9/site-packages/requests/models.py", line 975, in json
7|api  |     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
7|api  | requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by trojanx6** [comment]
I have the same error

**Comment by cop-discord** [comment]
ye its on latest 0.0.12 he will fix it its sum endpoint being buggy or maybe the use of simple json who knows

**Comment by dmytrostriletskyi** [comment]
Do you just execute this example — https://github.com/dmytrostriletskyi/threads-net/blob/main/examples/get_user.py

Or is it custom code? If yes, provide full example.

**Comment by dmytrostriletskyi** [comment]
Yeah, seems it is broken again. Kinda not stable endpoints on their side. I will try to fix it today or tomorrow, thanks.

**Comment by 6ky** [comment]
how do I contact you? I would like to understand how you RE threads I have tried with mitmproxy and routing my device requests to my PC and reading them but It seems like my SSL handshake is getting rejected only for instagram and threads, TLSv1.3 error for charles proxy apparently it tried using TLSv1.2

**Comment by 6ky** [comment]
Apologies if this is the wrong place to ask "new" to github

**Comment by cop-discord** [comment]
> Yeah, seems it is broken again. Kinda not stable endpoints on their side. I will try to fix it today or tomorrow, thanks.

all good man, good work so far

**Comment by dmytrostriletskyi** [comment]
@cop-discord, try new release, please — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.13
Works for you?

**Comment by DANTHEMANKING** [comment]
Everything worked fine 15 mins ago but now I get this:

An error occurred:  'NoneType' object has no attribute 'group'
