### ISSUE TITLE
New Version Error For Public API

### ISSUE THREAD

**Issue by kivancagaogluu** [dmytrostriletskyi/threads-net#23]
>>> from threads import Threads
>>> threads = Threads()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bluntk/.local/lib/python3.11/site-packages/threads/main.py", line 23, in __init__
    self.private_api = PrivateThreadsApi(username=username, password=password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluntk/.local/lib/python3.11/site-packages/threads/apis/private.py", line 46, in __init__
    self.user_id = self.get_user_id(username=username)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluntk/.local/lib/python3.11/site-packages/threads/apis/abstract.py", line 49, in get_user_id
    user_id_key_value = re.search('"user_id":"(\d+)",', response.text).group()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net/issues/20#issuecomment-1628383275

**Comment by dmytrostriletskyi** [comment]
Private API should work well, btw.

**Comment by kivancagaogluu** [comment]
Thank you for quick response but i do not have any interest for private api. Is there any way to use it without credentials

**Comment by RealWorldVesper** [comment]
To add here, I'm getting this error on both public and private consistently even with multiple attempts.  This is using V0.0.18

**Comment by dmytrostriletskyi** [comment]
@RealWorldVesper, I understood. Probably, I initialize public API even if you don't use it. Need to work in it as well, thanks.

**Comment by dmytrostriletskyi** [comment]
I have made a small fix, let's see if it works – https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.19

I will also add logging as well in the future so we better handle the issues because those sometimes hard to reproduce (API is not stable). Can you check it works for you? @RealWorldVesper @kivancagaogluu

**Comment by kivancagaogluu** [comment]
> > I have made a small fix, let's see if it works – [`v0.0.19` (release)](https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.19)
> > I will also add logging as well in the future so we better handle the issues because those sometimes hard to reproduce (API is not stable). Can you check it works for you? @RealWorldVesper @kivancagaogluu
> 
> that fixed the issue for me with the public API

I did not get any error. Seems like your last changes fixed the bug. Thank you
