### ISSUE TITLE
How to obtain User ID?

### ISSUE THREAD

**Issue by bryanseah234** [dmytrostriletskyi/threads-net#3]
Hi, stumbled across this repo and looks interesting. Would love to show my support and love for it. I took a quick look at the code, and realised the part about the User ID is not explained clearly. Where would one obtain user ID? And is the user ID for threadsapp the same for Instagram?

**Comment by dmytrostriletskyi** [comment]
Hi, @bryanseah234, thank you for the issue.

Yeah, basically the `id` of a user for `Threads` is the same as for `Instagram`. For instance, with this website you are able to fetch a user's Instagram identifier — https://commentpicker.com/instagram-user-id.php (check the screenshot below)

<img width="544" alt="Screenshot 2023-07-07 at 15 46 58" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/debd023b-dc75-4d60-9099-c5cacc5bd2d1">

On the provided example of `Mark Zuckerberg`'s Instagram account, it has identifier `314216` which is completely the same for Threads usage:

> https://github.com/dmytrostriletskyi/threads-net/blob/main/examples/get_user.py

```python
import json

from threads import Threads


if __name__ == '__main__':
    threads = Threads()
    user = threads.get_user(id=314216)

    print(json.dumps(user, indent=4))
```

```
➜  threads git:(main) ✗ python3 examples/get_user.py
{
    "data": {
        "userData": {
            "user": {
                "is_private": false,
                ...
                "pk": "314216",
                "full_name": "Mark Zuckerberg"
            }
        }
    },
}
```

**Comment by dmytrostriletskyi** [comment]
I have not worked with `Instagram API` yet and not found a way to fetch a user ID from `Thread API` either. I will investigate this part, but if you have any thoughts, let me know in this issue, please.

**Comment by dmytrostriletskyi** [comment]
I have found a Python library for Instagram and I see they have such an endpoint/method to fetch a user identifier by their username — https://github.com/adw0rd/instagrapi#basic-usage

At least, we can reuse this library and the method. At maximum and better, I will spend time on debugging the library and find out if I can send the same requests to Threads API as well.

**Comment by FastFingertips** [comment]
https://github.com/FastFingertips/threads-net/blob/main/examples/get_user_by_username.py

**Comment by dmytrostriletskyi** [comment]
@FastFingertips, thank you, good job.

I went a different way, basically now it is required to login via Instagram credentials to use getting a user method. I have done it because in the future there probably would be a support for creating posts and other create/edit things. So you would need «proper» auth.

https://github.com/dmytrostriletskyi/threads-net#disclaimer 
https://github.com/dmytrostriletskyi/threads-net#login
