### ISSUE TITLE
Spoiler

### ISSUE THREAD

**Issue by maksam07** [dmytrostriletskyi/threads-net#35]
Maybe use a spoiler for the code? So the library page wouldn't be so huge

<details>
  <summary>Spoiler warning</summary>
  
See: https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287
  ```
<details>
  <summary>Spoiler warning</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
</details>
  ```
  
</details>

**Comment by dmytrostriletskyi** [comment]
Nice idea, thank you! I will test how it looks.

**Comment by dmytrostriletskyi** [comment]
Done — https://github.com/dmytrostriletskyi/threads-net#public

<img width="845" alt="Screenshot 2023-07-11 at 13 19 05" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/d449536a-9cad-4756-ae32-0a886f4676a8">
