### ISSUE TITLE
PrivateThreadsApi(): Code logic for users with instagram but no threads account. 

### ISSUE THREAD

**Issue by FastFingertips** [dmytrostriletskyi/threads-net#36]
If a user has an Instagram account upon login but doesn't have a Threads account, the code may encounter a dilemma. In the future, you might want to disable certain functionalities based on whether the user only has an Instagram account and has logged in.

**Comment by maksam07** [comment]
Just don't use authorization if you don't have an account

**Comment by FastFingertips** [comment]
Is it not possible to perform simple operations such as searching for a user or retrieving user followers using only an Instagram token?

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net#initialization

> You can leave username and password arguments unspecified if you have no plans to use private API

If you are going to use only public API, you do not need Instagram username and password, just do not specify it.
