### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' (on private_api)

### ISSUE THREAD

**Issue by RealWorldVesper** [dmytrostriletskyi/threads-net#37]
"AttributeError: 'NoneType' object has no attribute 'get'" being thrown for any calls on private.

```import secretsFile
from threads import Threads
threads = Threads(username=secretsFile.INSTAGRAM_USERNAME, password=secretsFile.INSTAGRAM_PASSWORD)

## Get User ID

def getUserID(uname):

    return(threads.private_api.get_user_id(username=uname))

print(getUserID('zuck'))

Traceback (most recent call last):
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 4, in <module>
    threads = Threads(username=secretsFile.INSTAGRAM_USERNAME, password=secretsFile.INSTAGRAM_PASSWORD)
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/main.py", line 27, in __init__
    self.private_api = PrivateThreadsApi(username=username, password=password)
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/apis/private.py", line 47, in __init__
    self.user_id = self.get_user_id(username=username)
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/apis/private.py", line 61, in get_user_id
    user_id_as_string = response.json().get('user').get('pk')
AttributeError: 'NoneType' object has no attribute 'get'
```

Also on public, still getting "AttributeError: 'NoneType' object has no attribute 'group'"

```
from threads import Threads
threads = Threads()

## Get User ID

def getUserID(uname):

    return(threads.public_api.get_user_id(username=uname))

print(getUserID('zuck'))

Traceback (most recent call last):
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 12, in <module>
    print(getUserID('zuck'))
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 10, in getUserID
    return(threads.public_api.get_user_id(username=uname))
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/apis/abstract.py", line 56, in get_user_id
    user_id_key_value = re.search('"user_id":"(\\d+)",', response.text).group()
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by dmytrostriletskyi** [comment]
For the private `get_user_id`, it works for me, by the way:

<img width="888" alt="Screenshot 2023-07-10 at 23 20 38" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/c2e342d3-40ce-4ca4-9e93-e1c26f3ef999">

May it be that you are suspended? Let's check, please, execute this command and tell me if it works for you.

```
>>> user = threads.private_api.get_user(id=314216)
>>>
```

If not, probably you are suspended, but I am not sure, of course. By anyway, by making a few more methods calls, we can figure it out.

For the public `get_user_id`, I have created this docs chapter to explain what happens — 
https://github.com/dmytrostriletskyi/threads-net#user-identifier

**Comment by RealWorldVesper** [comment]
I realised that it didn't make sense to have consistent fails.

Removed 2FA on Instagram and immediately worked.

**Comment by dmytrostriletskyi** [comment]
Nice info, I will extend the docs about 2fa but i will work on supporting it as well.

**Comment by salmanrk** [comment]
I'm facing this issue even though there is no 2FA enabled on my account.

**Comment by alvasilvao** [comment]
> 

Me too. 2 days ago it worked but yesterday and today I am getting the "AttributeError: 'NoneType' object has no attribute 'get'" error

**Comment by salmanrk** [comment]
> 

Try updating the package. Apparently there was a change to the api from Threads side. It was resolved in the update.

**Comment by ML-Learning-2022** [comment]
I updated to the latest version, but using the public API reports an error AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ML-Learning-2022** [comment]
import json

from threads import Threads


if __name__ == '__main__':
    threads = Threads()

    thread_id = threads.public_api.get_thread_id(url_id='CuXFPIeLLod')
    print(thread_id)

    thread = threads.public_api.get_thread(id=thread_id)
    print(json.dumps(thread, indent=4))
Traceback (most recent call last):
  File "/root/ph/ph/threads/example.py", line 10, in <module>
    threads = Threads()
  File "/root/anaconda3/envs/THD/lib/python3.9/site-packages/threads/main.py", line 42, in __init__
    self.public_api = PublicThreadsApi()
  File "/root/anaconda3/envs/THD/lib/python3.9/site-packages/threads/apis/public.py", line 29, in __init__
    self.threads_api_token = self._get_threads_api_token()
  File "/root/anaconda3/envs/THD/lib/python3.9/site-packages/threads/apis/public.py", line 235, in _get_threads_api_token
    token_key_value = re.search('LSD",\\[\\],{"token":"(.*?)"},\\d+\\]', response.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
