### ISSUE TITLE
Worked 1X, since errors?

### ISSUE THREAD

**Issue by 6ky** [dmytrostriletskyi/threads-net#39]
it worked once, now im just getting errors: 'NoneType' object has no attribute 'group' across multiple functions this is due to this in your code tried debugging it im too tired gonna go to bed ill retry tomorrow:

where the error comes from in ur code:

`
    def get_user_id(self, username: str) -> int:
        """
        Get a user's identifier.

        Arguments:
            username (str): a users username.

        Returns:
            The user's identifier as an integer.
        """
        response = requests.get(
            url=f'https://www.instagram.com/{username}',
            headers=self.fetch_html_headers,
        )

        user_id_key_value = re.search('"user_id":"(\\d+)",', response.text).group()
        user_id = re.search('\\d+', user_id_key_value).group()

        return int(user_id)
`

**Comment by 6ky** [comment]
github not letting me format correctly anyways goodnight

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net#user-identifier
