### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by WTeam-Files** [dmytrostriletskyi/threads-net#4]
i got error when use:
thread = Threads()

which is error in requests Redirects.

**Comment by WTeam-Files** [comment]
> 

requests.exceptions.TooManyRedirects: Exceeded 30 redirects

**Comment by cop-discord** [comment]
is this fixed yet

**Comment by kirilkindan** [comment]
I still have it. how did you fix it?

**Comment by dmytrostriletskyi** [comment]
@WTeam-Files, @cop-discord, @kirilkindan, hi! 

Can you please try the latest release now and tell me if you still have the error — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.12

**Comment by RealWorldVesper** [comment]
If it's any assistance, I'm not getting the error "AttributeError: 'Threads' object has no attribute 'login'"

**Comment by dmytrostriletskyi** [comment]
@RealWorldVesper, each new version many changes code including breaking compatibility. Just download the latest release v0.0.14 and check the docs/examples on how to work with the project.

**Comment by RealWorldVesper** [comment]
@dmytrostriletskyi sure thing.  thanks for your great work on this.

**Comment by dmytrostriletskyi** [comment]
If you experience it again, reopen the issue or open a new one, please. Now we went far away from that moment, so that might be fixed already.
