### ISSUE TITLE
what happen

### ISSUE THREAD

**Issue by yekayee** [dmytrostriletskyi/threads-net#45]
Traceback (most recent call last):
  File "", line 20, in <module>
    created_thread = threads.private_api.create_thread(
  File "", line 252, in create_thread
    parameters_as_string['upload_id'] = self._upload_image(url=image_url)
  File "", line 445, in _upload_image
    headers = self.headers | {
AttributeError: 'PrivateThreadsApi' object has no attribute 'headers'

**Comment by yekayee** [comment]
threads\apis\private.py", line 256, in create_thread
    raise ValueError('Provided image URL does not match required format. Please, create GitHub issue')
ValueError: Provided image URL does not match required format. Please, create GitHub issue

**Comment by FastFingertips** [comment]
are you logged in

**Comment by dmytrostriletskyi** [comment]
Can you please provide a code to reproduce ao I can debug?

**Comment by MsLolita** [comment]
> Can you please provide a code to reproduce ao I can debug?

simple publishing without image results to this error
version 0.0.30
```
from threads import Threads
threads = Threads(username='username', password='password')

print(threads.private_api.create_thread(caption="Hello!"))
```

I fixed it by changing(function 'create_thread') " if url is not None: -> if url is None: "
![image](https://github.com/dmytrostriletskyi/threads-net/assets/58307006/88c72d33-7f8b-4247-94b7-11d66728ad25)

Now before this error is problem with login(((.

**Comment by dmytrostriletskyi** [comment]
I can better understand this issue once we resolve this one — https://github.com/dmytrostriletskyi/threads-net/issues/46

**Comment by dmytrostriletskyi** [comment]
Should be fixed in the latest release — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.35
