### ISSUE TITLE
no attribute headers

### ISSUE THREAD

**Issue by yekayee** [dmytrostriletskyi/threads-net#52]
when i try follow_user error

in follow_user
    headers=self.headers,
AttributeError: 'PrivateThreadsApi' object has no attribute 'headers'

**Comment by yekayee** [comment]
"""
Provide example of following and unfollowing a user from private Threads API.
"""
import os
import json

from threads import Threads

INSTAGRAM_USERNAME = os.environ.get('INSTAGRAM_USERNAME')
INSTAGRAM_PASSWORD = os.environ.get('INSTAGRAM_PASSWORD')


if __name__ == '__main__':
    threads = Threads(username=INSTAGRAM_USERNAME, password=INSTAGRAM_PASSWORD)

    following = threads.private_api.follow_user(id=314216)
    print(json.dumps(following, indent=4))

**Comment by ezad313** [comment]
I have the same problem, how did you solve it?
