### ISSUE TITLE
error when login

### ISSUE THREAD

**Issue by yekayee** [dmytrostriletskyi/threads-net#55]
user_id_as_string = response.json().get('user').get('pk')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dmytrostriletskyi** [comment]
@yekayee, can you recreate the issue using this button?

<img width="1265" alt="Screenshot 2023-07-13 at 16 35 32" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/c511aa37-2c37-4cfa-9555-9c532fd618d8">

There are a few fields to be answered that will help me to solve the problem.
