### ISSUE TITLE
error when login (bug)

### ISSUE THREAD

**Issue by yekayee** [dmytrostriletskyi/threads-net#57]
error get user id 
threads\apis\private.py", line 76, in get_user_id
    user_id_as_string = response.json().get('user').get('pk')
AttributeError: 'NoneType' object has no attribute 'get'

INSTAGRAM_USERNAME = os.environ.get('INSTAGRAM_USERNAME')
INSTAGRAM_PASSWORD = os.environ.get('INSTAGRAM_PASSWORD')

threads = Threads(username=INSTAGRAM_USERNAME, password=INSTAGRAM_PASSWORD)

**Comment by dmytrostriletskyi** [comment]
What is your version of Python and the library?

**Comment by yekayee** [comment]
python 3.9 and new 0.0.42

**Comment by dmytrostriletskyi** [comment]
Your Instagram account is not suspended or blocked, you can log in into it on https//:instagram.com?

**Comment by yekayee** [comment]
user another account same problem

**Comment by dmytrostriletskyi** [comment]
I tried the same and it worked, basically — https://github.com/dmytrostriletskyi/threads-net/blob/main/examples/private/get_user.py

May it be your IP is blocked somehow? Can you install any free VPN and try via it?

**Comment by dmytrostriletskyi** [comment]
@yekayee, so you tried both with and without VPN?

**Comment by yekayee** [comment]
yes sir

**Comment by dmytrostriletskyi** [comment]
For me, it is hard to say, to be honest. 

The library needs to work on logging, proper requests status handling, etc. It is in the roadmap, but not a priority until all the functionality is covered, I think.

Are you capable of debugging it on yourself? For instance, find a place of the private API file (where the library is installed) and save the `response.text` to a file and then send it here?

I can also try your username and password if you don't mind of sharing it.

**Comment by evandroamparo** [comment]
I was getting a similar error message because of 'too many requests' or something like that.
Now I'm using a VPN and the problem is the token.

`_get_instagram_api_token` returns an empty string because it cannot find 'Bearer IGT:2:' in the response.

![image](https://github.com/dmytrostriletskyi/threads-net/assets/1426462/3c2a976a-75fb-4a73-aa1d-a428562f8a34)

response.text is:

```
{
    "layout": {
        "bloks_payload": {
            "data": [],
            "props": [
                {
                    "id": "-6917714003244327204",
                    "name": "ttrc_instance_id"
                },
                {
                    "id": "2231046902902521263",
                    "name": "override_login_success_action"
                }
            ],
            "error_attribution": {
                "logging_id": "{\\"callsite\\":\\"{\\\\\\"product\\\\\\":\\\\\\"bloks_caa_login\\\\\\",\\\\\\"feature\\\\\\":\\\\\\"com.bloks.www.bloks.caa.login.async.send_login_request\\\\\\",\\\\\\"integration\\\\\\":\\\\\\"bloks_screen\\\\\\",\\\\\\"oncall\\\\\\":\\\\\\"caa_login\\\\\\"
                }\\",\\"push_phase\\":\\"C3\\",\\"version\\":1,\\"request_id\\":\\"AYMuaRV5nupCiYNPKmZRcd-\\"}"
            },
            "tree": {
                "㐟": {
                    "#": " (bk.action.core.TakeLast, (bk.action.core.TakeLast, (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \\"login_type\\", \\"login_source\\"), (bk.action.array.Make, \\"Password\\", \\"Login\\"))), (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \\"end_point\\"), (bk.action.array.Make, \\"generic_error_dialog\\"))), (bk.action.qpl.MarkerEndV2, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.i32.Const, 87), (bk.action.tree.Make, (bk.action.i32.Const, 13704)))), null, (bk.action.core.TakeLast, (bk.action.core.TakeLast, (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \\"login_type\\", \\"login_source\\"), (bk.action.array.Make, \\"Password\\", \\"Login\\"))), (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \\"end_point\\"), (bk.action.array.Make, \\"redirect_checkpoint\\"))), (bk.action.qpl.MarkerEndV2, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.i32.Const, 87), (bk.action.tree.Make, (bk.action.i32.Const, 13704)))), (bk.action.logging.LogEvent, \\"caa_login_client_events_ig\\", \\"\\", (bk.action.map.Make, (bk.action.array.Make, \\"core\\", \\"login_params\\"), (bk.action.array.Make, (bk.action.map.Make, (bk.action.array.Make, \\"event\\", \\"event_category\\", \\"event_flow\\", \\"event_request_id\\", \\"event_step\\", \\"is_dark_mode\\", \\"exception_code\\", \\"exception_message\\", \\"exception_type\\", \\"extra_client_data\\", \\"logged_out_identifier\\", \\"logged_in_identifier\\", \\"waterfall_id\\"), (bk.action.array.Make, \\"redirection_to_checkpoint\\", \\"checkpoint\\", \\"checkpoint\\", \\"19ecaa54-8b90-42ec-8b7a-6ba31e2ea567\\", \\"checkpoint_redirect\\", (ig.action.IsDarkModeEnabled), (bk.action.i32.Const, 0), \\"\\", \\"\\", (bk.action.map.Make, (bk.action.array.Make, \\"login_source\\", \\"login_credential_type\\"), (bk.action.array.Make, \\"Login\\", \\"Password\\")), \\"\\", \\"\\", \\"d963fc01-7f26-4538-8487-698d6a872315\\")), (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make))))), (bk.action.i32.Const, 1), (bk.action.caa.PresentCheckpointsFlow, \\"{\\\\\\"error\\\\\\": {\\\\\\"uid\\\\\\": null,\\\\\\"code\\\\\\": 1,\\\\\\"message\\\\\\":\\\\\\"Unmapped IG Error: This IG Error was not mapped to an Error Code. To fix it, update the error tool under \'CAA\' to map it to an Error Code.\\\\\\",\\\\\\"error_user_title\\\\\\":\\\\\\"\\\\\\",\\\\\\"error_subcode\\\\\\": 3540001,\\\\\\"error_user_msg\\\\\\":\\\\\\"challenge_required\\\\\\",\\\\\\"error_data\\\\\\": {\\\\\\"url\\\\\\":\\\\\\"https:\\\\\\\\\\\\/\\\\\\\\\\\\/i.instagram.com\\\\\\\\\\\\/challenge\\\\\\\\\\\\/AXEhu_plKmHCWw75FRw2JMxm7V_bwuD4A96ptiTSpFLLiHO9RrWLe7B00bin-IXhOSX7\\\\\\\\\\\\/AfxYHQxspT6xSYF7DlXKtYLsdvBREf_ruktVrmlyy4QTXDBKGUNJPbLkCXlp0Osu9xkf3RvRq8Pi9A\\\\\\\\\\\\/\\\\\\",\\\\\\"api_path\\\\\\":\\\\\\"\\\\\\\\\\\\/challenge\\\\\\\\\\\\/AXEhu_plKmHCWw75FRw2JMxm7V_bwuD4A96ptiTSpFLLiHO9RrWLe7B00bin-IXhOSX7\\\\\\\\\\\\/AfxYHQxspT6xSYF7DlXKtYLsdvBREf_ruktVrmlyy4QTXDBKGUNJPbLkCXlp0Osu9xkf3RvRq8Pi9A\\\\\\\\\\\\/\\\\\\",\\\\\\"hide_webview_header\\\\\\": true,\\\\\\"lock\\\\\\": true,\\\\\\"logout\\\\\\": false,\\\\\\"native_flow\\\\\\": true,\\\\\\"flow_render_type\\\\\\": 0,\\\\\\"challenge_context\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"step_name\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"\\\\\\\\\\\\\\", \\\\\\\\\\\\\\"nonce_code\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"AfzkxXcFlx6kKiq1QmbNX4tdOOT0BRbiVgksO-xG31ktaDktmxH5P9tD4YElEbUGczEjA0mwd-d6Wg\\\\\\\\\\\\\\", \\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"AXGzCC15PAJWdmhrt4xW1XLSGkoAAihLPUCEkW8qxh4B5q8v2F2LWEkJMABTvD6bfLrd\\\\\\\\\\\\\\", \\\\\\\\\\\\\\"first_factor_code\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"NPFpDAXxmfQXKB62hz9bPyaIQ5BJKR0Wq43xLokTomu6aWwnAmOW1Xt73FzOUYFz\\\\\\\\\\\\\\", \\\\\\\\\\\\\\"is_stateless\\\\\\\\\\\\\\": false, \\\\\\\\\\\\\\"present_as_modal\\\\\\\\\\\\\\": false}\\\\\\"
                            }
                        }
                    }\\", (bk.action.core.GetArg, 0)), (bk.action.map.Make, (bk.action.array.Make, \\"should_dismiss_loading\\"), (bk.action.array.Make, (bk.action.bool.Const, false)))))"
                }
            }
        }
    },
    "status": "ok"
}
```

**Comment by salmanrk** [comment]
I used it 19 hours ago to login and create one thread and it worked. Now I tried again and it didn't log in. Then I just noticed I got an email from instagram after that thread i posted. 


"We noticed a login from a device you don't usually use.
 
If this was you, you won’t be able to access certain security and account settings for a few days. You can still access these settings from a device you’ve logged in with in the past."

**Comment by DANTHEMANKING** [comment]
I have the same error.

**Comment by chipoel** [comment]
i had same error beffore, what i did to fix is

remove this section
INSTAGRAM_USERNAME = os.environ.get('INSTAGRAM_USERNAME')
INSTAGRAM_PASSWORD = os.environ.get('INSTAGRAM_PASSWORD')

and just use this part

threads = Threads(username='username', password='password') // replace username and password with your threads user pass

**Comment by yekayee** [comment]
> i had same error beffore, what i did to fix is
> 
> remove this section INSTAGRAM_USERNAME = os.environ.get('INSTAGRAM_USERNAME') INSTAGRAM_PASSWORD = os.environ.get('INSTAGRAM_PASSWORD')
> 
> and just use this part
> 
> threads = Threads(username='username', password='password') // replace username and password with your threads user pass

still error bro
    user_id_as_string = response.json().get('user').get('pk')
AttributeError: 'NoneType' object has no attribute 'get

**Comment by dmytrostriletskyi** [comment]
@evandroamparo, @yekayee, from [this](https://github.com/dmytrostriletskyi/threads-net/issues/57#issuecomment-1634604526) post's error I see that inside it there is a mention of required challenge:

<img width="523" alt="Screenshot 2023-07-14 at 13 09 52" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/82222ebe-e4ea-4a5b-8168-4b2b22e007e4">

As I researched, sometimes Instagram might ask the challenge if it is suspicious about all requests are sent my a machine, but a real human. 

I have seen how other Instagram libraries solved this and seems it is pretty straightforward. I will put it into my roadmap as high priority.

@yekayee, @evandroamparo maybe you can provide me your username and password? Then I will be able to test it locally because it would be hard to reproduce. Yeah, only if those accounts are testing accounts, not real. If you are willing to do so, send me them by e-mail: dmytro.striletskyi@gmail.com

**Comment by evandroamparo** [comment]
Thank you, @dmytrostriletskyi. That is my real account. Please let me know if you need help testing this.

**Comment by yekayee** [comment]
thanks sir its work

**Comment by maksam07** [comment]
```py
response = requests.get(url=f'{self.INSTAGRAM_API_URL}/users/{username}/usernameinfo/', headers=self.headers)
print(response.text)
```
->
```
{"message":"Please wait a few minutes before you try again.","status":"fail"}
```
