### ISSUE TITLE
Implement ability to create a post

### ISSUE THREAD

**Issue by MarkParker5** [dmytrostriletskyi/threads-net#6]

**Comment by Jxck-S** [comment]
+1 would like to use it for my ElonJet account.

In addition to basic posting these would be nice. 
- Post with image
- Post a reply

**Comment by dmytrostriletskyi** [comment]
@MarkParker5, hi! Thanks for the interest in the project.

I have just added the ability to add threads (posts), there is still work to do, but already you can post text.

https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.12
https://github.com/dmytrostriletskyi/threads-net#create-thread
