### ISSUE TITLE
limit ?

### ISSUE THREAD

**Issue by yekayee** [dmytrostriletskyi/threads-net#61]
TypeError: 'NoneType' object is not subscriptable

**Comment by dmytrostriletskyi** [comment]
Please, recreate the issue with this:

<img width="1272" alt="Screenshot 2023-07-14 at 14 18 08" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/03c45014-b99d-402e-9f0b-5eec01bea5e3">

There are predefined questions and a guide to a issue creator, which will help maintainers to answer the code. Example — https://github.com/dmytrostriletskyi/threads-net/issues/60
